[buildPlans.iosevka-marcus-qpe]
family = "Iosevka Marcus QPE"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-marcus-qpe.variants.design]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-bilateral-serifed"
capital-c = "serifless"
capital-d = "more-rounded-bilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-serifed"
capital-i = "serifed"
capital-j = "descending-serifed-both-sides"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "closed-serifless"
capital-q = "crossing-curly-tailed"
capital-r = "curly-open-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "straight-vertical-sides-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "double-storey-toothless-rounded"
b = "toothless-corner-serifless"
c = "serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey"
h = "straight-serifless"
i = "tailed-serifed"
j = "serifless"
k = "curly-serifless"
l = "tailed-serifed"
m = "short-leg-serifless"
p = "earless-corner-serifless"
q = "earless-corner-diagonal-tailed-serifless"
r = "top-serifed"
t = "bent-hook-short-neck2"
u = "tailed-serifless"
v = "curly-serifless"
w = "cursive-serifed"
y = "cursive-motion-serifed"
z = "straight-serifless-with-horizontal-crossbar"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-tailed-serifless"
lower-iota = "flat-tailed"
lower-lambda = "curly-turn"
lower-mu = "toothless-rounded-serifless"
lower-tau = "flat-tailed"
cyrl-capital-u = "straight-serifless"
zero = "slashed"
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open-non-crossing"
five = "oblique-arched"
six = "open-contour"
seven = "bend-serifless-crossbar"
eight = "crossing-asymmetric"
nine = "open-contour"
diacritic-dot = "round"
asterisk = "turn-hex-mid"
underscore = "high"
caret = "medium"
paren = "flat-arc"
brace = "curly"
number-sign = "upright-tall"
ampersand = "et-tailed"
at = "fourfold"
dollar = "interrupted"
percent = "rings-continuous-slash-also-connected"
bar = "natural-slope"
question = "corner"
pilcrow = "low"
cent = "open"
partial-derivative = "curly-bar"
lig-ltgteq = "flat"
lig-neq = "more-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "without-notch"

[buildPlans.iosevka-marcus-qpe.ligations]
inherits = "dlig"

[buildPlans.iosevka-marcus-qpe.widths.normal]
shape = 720
menu = 5
css = "normal"

#[buildPlans.iosevka-marcus-qpe.metric-override]
#winMetricDescenderPad = 50
#leading = 1390
#descender = -260